# Configuracion de Persistencia del componente.

# motor = h2     -> conexion REAL a H2 embebido en archivo.
# motor = mysql  -> conexion simulada
motor=h2

# AUTO_SERVER=TRUE permite que las cuatro aplicaciones abran la MISMA base al tiempo desde JVM distintas.
# La ruta es relativa al directorio desde donde se ejecuta el .jar.
h2.url=jdbc:h2:file:./datos/inventario;AUTO_SERVER=TRUE;MODE=MySQL
h2.usuario=sa
h2.clave=

mysql.url=jdbc:mysql://localhost:3306/inventariodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
mysql.usuario=root
mysql.clave=root
mysql.timeoutSegundos=2
