
# capa de Persistencia del componente.

# motor = h2     -> conexion REAL a H2 embebido en archivo.
# motor = mysql  -> ls conexion se simula

motor=h2

s
h2.url=jdbc:h2:file:./datos/inventario;AUTO_SERVER=TRUE;MODE=MySQL
h2.usuario=sa
h2.clave=

mysql.url=jdbc:mysql://localhost:3306/inventariodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
mysql.usuario=root
mysql.clave=root
mysql.timeoutSegundos=2
